# Generated by Django 5.1.3 on 2024-11-09 18:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(default=dict)),
                ('geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
